language: ruby
script: "./script/cibuild"
notifications:
  email: false
branches:
  only:
    - gh-pages
    - /.*/
before_install:
- openssl version
- openssl ciphers -v 'ALL:eNULL' | sed -e 's/:/ /: /g'
sudo: false
cache: bundler
