#list of GitHub organization usernames, grouped by type
organizations:

  United States:
    - adlnet
    - cfpb
 #   - EducationDataInitiative
    - erdc-cm
    - fcc
    - gsa
    - GSA-OCSIT
    - hhs
    - LibraryOfCongress
    - nasa
    - nationalparkservice
    - NCIP
    - nrel
    - opengovplatform
    - presidential-innovation-fellows
    - usagov
    - USDepartmentofLabor
    - USEPA
    - usgs
    - usnationalarchives
    - whitehouse
    - usasearch
    - commercegov
    - usda
 #   - USDA-ERS
 #   - usinterior
    - CMSgov
    - IMLS

  Argentina:
    - gcba

  Canada:
    - nsgov
    - pwgsc

  Finland:
    - avoinministerio
    - City-of-Helsinki

  Norway:
    - difi

  United Kingdom:
    - alphagov
    - lichfield-district-council
    
  Estonia:
    - vvk-ehk

  U.S. States:
    - nysenate
#    - wsdot
    - nys-its

  U.S. County:
    - sfcta
    - miamidade
    - pueblocounty

  U.S. City:
    - chicago
#    - sfgov
    - cityofnewyork
    - octolabs
    - city-of-bloomington
    - city-of-bellingham
    - egovpdx
    - NYCComptroller

  Civic Hackers:
    - codeforamerica
    - sunlightlabs
    - opengovfoundation
    - open-city
    - gitmachines
    - dobtco
    - openplans
    - okfde
    - okfn
    - civicindustries
    - localdata
    
#global settings
title: "Government and GitHub"
description: "Stories of open data, open source, and open collaboration"
permalink: "/stories/:title"

#build settings
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
root: "/"
paginate: 10
