# global settings
title: "GitHub and Government"
description: "GitHub helps government build software better, together"
permalink: "/stories/:title"
url: http://government.github.com
relative_permalinks: false
analytics_account: "UA-3769691-28"

# build settings
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json"]
paginate: 6
markdown: kramdown
gems:
  - jekyll-sitemap

# prose settings
prose_server: "http://prose.io"
prose:
  siteurl: "http://government.github.com"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "story"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Image"
          placeholder: "/images/YOUR_IMAGE.png"
          value: ""
          type: "text"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          options:
            - name: "Open Government"
              value: "open government"
            - name: "Open Data"
              value: "open data"
            - name: "Open Source"
              value: "open source"
