#list of GitHub organization usernames, grouped by type
organizations:

  United States:
    - adlnet
    - cfpb
 #   - EducationDataInitiative
    - erdc-cm
    - fcc
    - gsa
    - GSA-OCSIT
    - hhs
    - LibraryOfCongress
    - nasa
    - nationalparkservice
    - NCIP
    - nrel
    - opengovplatform
    - presidential-innovation-fellows
    - usagov
    - USDepartmentofLabor
    - USEPA
    - usgs
    - usnationalarchives
    - whitehouse
    - usasearch
    - commercegov
    - usda
 #   - USDA-ERS
 #   - usinterior

  Argentina:
    - gcba

  Canada:
    - nsgov
    - pwgsc

  Finland:
    - avoinministerio
    - City-of-Helsinki

  Norway:
    - difi

  United Kingdom:
    - alphagov
    - lichfield-district-council

  State:
    - nysenate
#    - wsdot
    - nys-its

  County:
    - sfcta
    - miamidade
    - pueblocounty

  City:
    - chicago
#    - sfgov
    - cityofnewyork
    - octolabs
    - city-of-bloomington
    - city-of-bellingham
    - egovpdx

  Civic Hackers:
    - codeforamerica
    - sunlightlabs
    - opengovfoundation

#global settings
title: "Government and GitHub"
description: "Stories of open data, open source, and open collaboration"

#build settings
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
root: "/"